### ISSUE TITLE
Proposals

### ISSUE THREAD

**Issue by kristianmandrup** [xpepermint/objectschemajs#2]
Also allow schema extension via `extends` property. Also generalise registry for both defaults and fakes ;)

```js
const registry = {
  defaults,
  fakes
}

const user = {}
user.admin = new Schema({
  name: `AdminUser `
  extends: `User`,
  registry,
  ...
})
```

That would be awesome, elegant and make for more reuse, slim code and nice convention IMO.

Also, make `Number` a valid type, either an alias for `Integer` or let it be any `Integer|Float` ?

Schemas could/should be added in their own registry and when instantiated via `new Document` the extends is only then "lazily" resolved.

Personally I almost never use or expose classes themselves, only factory methods. 
Was just thinking, `export default` is most often an anti-pattern which tends to box you in.

```js
createSchema({
}
```

Then the schema factory method could be made to register the new instance as well. Possibly you could even configure the factory method, ie. create a factory for the schema factory method... a `schemaMaster`. But perhaps I'm taking this too far? Just keeping options open ("over designing"? YAGNI!?)

```js
const { createSchema } = schemaMaster({ registry })

schemas.user = createSchema({
  name: 'user',
  extends: schemas.base, // or use name of registered schema
  ...
})
```

Then you can pass whatever registry adheres to a certain API: 
- `set` and `get` by schema name.

```js
class Registry {
  construtor() {
    this.store = {}
  }

  get(name) {
    this.store[name]
  }

  set(name, schema) {
    this.store[name] = schema
  }
}


export class SchemaMaster {
  constructor(opts = {}) {
    this.registry = opts.registry || new Registry()
  }

  get(name) {
    this.registry.get(name)
  }

  set(name, schema) {
    this.registry.set(name, schema)
  }

  createSchema(obj) => {
    const schema = new Schema(obj)
    schema.registry = this.registry
    schema.master = this
    this.set(schema.name, schema)
    return schema
  }
}

export schemaMaster(opts = {}) => {
  return new SchemaMaster(opts)
})
```

**Comment by xpepermint** [comment]
I like your proposals. Let me think ...

**Comment by xpepermint** [comment]
Btw... what do you mena by:
> Schemas could/should be added in their own registry and when instantiated via new Document the extends is only then "lazily" resolved.

**Comment by xpepermint** [comment]
I've checked the [Float and Integer](https://github.com/xpepermint/typeablejs/) types. The `Float` is actually the `Number` so if you just need some number type use `Float`. I could add an alias `Number` but that would just add a some duplicated code.

**Comment by kristianmandrup** [comment]
I just assumed `Number` would be valid. Please add alias `Number`, it is a basic javascript type.

**Comment by kristianmandrup** [comment]
I mean, when you create the schema and extend, it could either be resolved immediately by looking for the schema to extend in the schema registry, or it could be resolve later when all schemas have been defined, ie `schemaMaster.resolve()` or sth, that way there is no ordering problem, that you have to register a schema before another in order to extend it. The lazy resolve could be possible by name, whereas using a schema (object) directly would have to be immediate.

**Comment by kristianmandrup** [comment]
Let me try this out ;) Then we see... could also be an optional layer on top

**Comment by xpepermint** [comment]
`Number` type is now supported.

**Comment by xpepermint** [comment]
The `faker` API https://github.com/xpepermint/objectschemajs/pull/1 is merged and available for download.

**Comment by xpepermint** [comment]
You are mentioning the "lazily" resolved fields. This feature already exists and is described as `document nesting with support for self referencing`. This feature was inspired by GraphQL schema.

Instead of assigning an Object to the `Schema.fields` you assign a function which returns the Object.

```js
new Schema({
  fields: () => ({
    title: { type: 'String' }
  })
});
```

**Comment by kristianmandrup** [comment]
Cool :)

**Comment by xpepermint** [comment]
NOTICE: Version `v4` has a new API.
