### ISSUE TITLE
API rethink

### ISSUE THREAD

**Issue by xpepermint** [xpepermint/objectschemajs#5]
The current API is good but I think it could be better and more aligned with TypeScript. Currently the main issue is that the document does not provide typescript information about the fields. 

New API concept/design proposal:

```js
class Book extends Document {
  public title: string;

  constructor (data?) {
    super();
    this.defineField('title', {type: 'String'});
    this.populate(data);
  }
}

class User extends Document {
  public name: string;
  public books: Book[] = [];

  constructor (data?) {
    super();
    this.setValidator('isCool', () => true);
    this.setHandler('404', () => false);
    this.defineField('name', {type: 'String'});
    this.defineField('book', {type: [Book]});
    this.populate(data);
  }
}
```

**Comment by kristianmandrup** [comment]
Please write some code/API sketches for different ideas/options. Then weigh pros vs. cons.

**Comment by xpepermint** [comment]
Problems of the current concept:
- Document configuration, fields and methods are decoupled from the actual document.
- Magic and less natural javascript code.
- Not TypeScript friendly (e.g. typescript doesn's know that fields exist).

Benefits of the new proposal:
- A document is defined just by extending a javascript class.
- Configuration, fields and methods are defined directly on that class.
- Less magic and natural javascript code.
- TypeScript friendly
- Intuitive design (e.g. you can easily use decorators).

**Comment by matjazgros** [comment]
I like the idea, it makes API easier and TypeScript friendly.

**Comment by xpepermint** [comment]
Version `v4` is now completed and ready for download.
